### ISSUE TITLE
게임 초기화 모듈 구현

### ISSUE THREAD

**Issue by gaeul910** [gaeul910/Dream-Cat-Simulator#8]
게임을 처음 실행할 때, 사용자 정보 등록 및 상태 정보 초기화 기능을 구현하여야 합니다.
loadGame 모듈에서 만약 게임 저장 파일이 없다면 해당 모듈을 실행합니다.
환영 메세지와 함께 사용자 이름과 개냥이 이름을 입력받아 PlayerData 구조체에 저장하고, 상태값을 다음과 같이 설정합니다.
hunger=1000
health=1000
delight=500
normal=750
sadness=0
anger=0
friendship=0

위 과정이 끝나면 저장 모듈을 실행해 정보를 저장하고 return한 후, loadGame 역시 종료합니다.

**Comment by Choi-Eunrak** [comment]
된거 같은데 문제있으면 말해주세용
